name: Build and deploy on Push

on:
 - push

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/run-maven-with-sonar.yaml@v1.0.0
    with:
      maven-goal: deploy
      java-version: 17
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
