---
name: Cleanup Old Maven Artifacts Versions
run-name: "${{ github.event_name }} - ${{ github.actor }}"
on:
    schedule:
      - cron: "10 0 * * 0" # Runs weekly on Sunday at midnight + 10
    workflow_dispatch:
      inputs:
        threshold-days:
          description: "Number of days to keep container versions"
          required: false
          default: "7"
        included-patterns:
          description: "Patterns to include for deletion"
          required: false
          default: "*SNAPSHOT*"
        excluded-patterns:
          description: "Patterns to exclude from deletion"
          required: false
          default: "release*"
        dry-run:
          description: "Enable dry-run mode"
          required: false
          default: "false"
          type: "boolean"
        debug:
          description: "Enable debug mode"
          required: false
          default: "false"
          type: "boolean"
jobs:
    cleanup:
      runs-on: ubuntu-latest

      steps:
        - name: "Summary"
          run: |
            echo "**Event**: ${{ github.event_name }}"
            echo "**Actor**: ${{ github.actor }}"
            echo "**Threshold days**: ${{ github.event.inputs.threshold-days || 8 }}"
            echo "**Included patterns**: ${{ github.event.inputs.included-patterns  || '*SNAPSHOT*' }}"
            echo "**Excluded patterns**: ${{ github.event.inputs.excluded-patterns || 'latest,release*,*.*' }}"
            echo "**Dry-run**: ${{ github.event.inputs.dry-run || 'false' }}"
            echo "**Debug**: ${{ github.event.inputs.debug || 'false' }}"
        - name: Run Maven Cleanup Action
          uses: netcracker/qubership-workflow-hub/actions/container-package-cleanup@main
          with:
            threshold-days: ${{ github.event.inputs.threshold-days || 14 }}
            included-patterns: ${{ github.event.inputs.included-patterns || '*SNAPSHOT*' }}
            excluded-patterns: ${{ github.event.inputs.excluded-patterns || 'latest,release*,*.*' }}
            debug: ${{ github.event.inputs.debug || 'false' }}
            dry-run: ${{ github.event.inputs.dry-run || 'false' }}
            package-type: maven
          env:
            PACKAGE_TOKEN: ${{ secrets.GH_RWD_PACKAGE_TOKEN }}